### ISSUE TITLE
masternode list full command

### ISSUE THREAD

**Issue by ericleroy01** [nyerium-core/nyerium#2]
_masternode list full_  command return an empty array []

based on other wallets, result should display data with following structure

| Field Size | Field Name | Data type | Description |
| ---------- | ----------- | --------- | -------- |
| 41 | vin | CTxIn | The unspent output which is holding 1000 AIRIN
| # | addr | CService | Address of the main 1000 AIRIN unspent output
| 33-65 | pubKeyCollateralAddress | CPubKey | CPubKey of the main 1000 AIRIN unspent output
| 33-65 | pubKeyMasternode | CPubKey | CPubKey of the secondary signing key (For all other messaging other than announce message)
| 71-73 | sig | char[] | Signature of this message
| 8 | sigTime | int64_t | Time which the signature was created
| 4 | nProtocolVersion | int | The protocol version of the masternode
| # | lastPing | CMasternodePing | The last known ping of the masternode

**Comment by nyerium-core** [comment]
Will add this to future versions.
