### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by hbheiner** [nyerium-core/nyerium#5]
wallet crash if i try to unlock with password...

...but password is not wrong
![nyerium](https://user-images.githubusercontent.com/5843199/41292667-8565a4b0-6e53-11e8-9cb3-e2c43003f0d0.jpg)

**Comment by nyerium-core** [comment]
Go to the folder %appdata%\nyerium and copy the wallet.dat, masternode.conf and nyerium.conf to a new location
The delete the content of the %appdata%\nyerium folder. Copy and paste the 3 files back to the folder and restart your nyerium-qt wallet
