### ISSUE TITLE
Notice of Copyright Violation

### ISSUE THREAD

**Issue by Iconoclasta** [nyerium-core/nyerium#6]
This is an official notice of Copyright violation against the PIVX developers in which this project has been forked from. The MIT copyright license, and subsequent copyright headers in source files have been modified to explicitly exclude the PIVX developers from all copyrights.

You are hereby notified of an intention to pursue further action if this issue is not acknowledged and formally addressed with a resolution timeframe commitment wherein. Failure to acknowledge and correct the violation will result in a formal DMCA takedown notice filed with GitHub Proper after no less than five business days from the date of this notice.

Explicit acknowledgement and referencing progress to maintain compliance MUST be noted in this issue's comments or referred to in any subsequent pull requests to this repository

File in question:

      nyerium/LICENSE

**Comment by nyerium-core** [comment]
hey Iconoclasta, not sure which file you are refering to, but i thought we tried to keep all references to PIVX in the code. If we could be more specific, that will help in addressing the issue.

![image](https://user-images.githubusercontent.com/37948087/45255444-468ad900-b38f-11e8-9fb0-0b073ba21b37.png)

**Comment by Iconoclasta** [comment]
Hey, sorry for the delay in replying. 

The issue we have found on yours and plenty other repositories is that you've apparently "re-licensed" our code, rather than "sub-licensed". This is so because there is a hierarchy in licensing files and LICENSE is higher than COPYING (please refer to this link to understand what I mean: https://i.imgur.com/l1MgVDo.gif ). To best address this issue I would recommend to either simply delete the LICENSE file (which currently adds no apparent value), or re-purpose the LICENSE file for a different copyright notice than MIT (Apache or GNU for example).

**Comment by nyerium-core** [comment]
> Hey, sorry for the delay in replying.
> 
> The issue we have found on yours and plenty other repositories is that you've apparently "re-licensed" our code, rather than "sub-licensed". This is so because there is a hierarchy in licensing files and LICENSE is higher than COPYING (please refer to this link to understand what I mean: https://i.imgur.com/l1MgVDo.gif ). To best address this issue I would recommend to either simply delete the LICENSE file (which currently adds no apparent value), or re-purpose the LICENSE file for a different copyright notice than MIT (Apache or GNU for example).

Hey, the issue is resolved. Please check again and let me know if there is anything else. thx

**Comment by Iconoclasta** [comment]
Thank's for your collaboration. This issue is now solved. I wish this project the best.
